config/routes.rb
Mediacore::Application.routes.draw do
  resources :episodes

  resources :series

  match 'series/episodes/:id' => 'series#episodes'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :series
end

app/models/series.rb
class Series < ActiveRecord::Base
  has_many :episodes

  def episode_count
    return episodes.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  # GET /episodes
  # GET /episodes.xml
  def index
    @episodes = Episode.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @episodes }
    end
  end

  # GET /episodes/1
  # GET /episodes/1.xml
  def show
    @episode = Episode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @episode }
    end
  end

  # GET /episodes/new
  # GET /episodes/new.xml
  def new
    @episode = Episode.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @episode }
    end
  end

  # GET /episodes/1/edit
  def edit
    @episode = Episode.find(params[:id])
  end

  # POST /episodes
  # POST /episodes.xml
  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to(@episode, :notice => 'Episode was successfully created.') }
        format.xml  { render :xml => @episode, :status => :created, :location => @episode }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @episode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /episodes/1
  # PUT /episodes/1.xml
  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to(@episode, :notice => 'Episode was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @episode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.xml
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to(episodes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  # GET /series
  # GET /series.xml
  def index
    @series = Series.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @series }
    end
  end

  # GET /series/1
  # GET /series/1.xml
  def show
    @series = Series.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @series }
    end
  end

  # GET /series/new
  # GET /series/new.xml
  def new
    @series = Series.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @series }
    end
  end

  # GET /series/1/edit
  def edit
    @series = Series.find(params[:id])
  end

  # POST /series
  # POST /series.xml
  def create
    @series = Series.new(params[:series])

    respond_to do |format|
      if @series.save
        format.html { redirect_to(@series, :notice => 'Series was successfully created.') }
        format.xml  { render :xml => @series, :status => :created, :location => @series }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @series.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /series/1
  # PUT /series/1.xml
  def update
    @series = Series.find(params[:id])

    respond_to do |format|
      if @series.update_attributes(params[:series])
        format.html { redirect_to(@series, :notice => 'Series was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @series.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.xml
  def destroy
    @series = Series.find(params[:id])
    @series.destroy

    respond_to do |format|
      format.html { redirect_to(series_index_url) }
      format.xml  { head :ok }
    end
  end

  def episodes
    @series = Series.find(params[:id])

    e = Episode.arel_table
    episode_count = e.group(e[:series_id]).project(e[:series_id], e[:episode_no].count(e[:series_id]).as('episode_count'))

    #@episode_counts = @series.episodes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :episode_no %><br />
    <%= f.text_field :episode_no %>
  </div>
  <div class="field">
    <%= f.label :season_no %><br />
    <%= f.text_field :season_no %>
  </div>
  <div class="field">
    <%= f.label :series_id %><br />
    <%= f.text_field :series_id %>
  </div>
  <div class="field">
    <%= f.label :imdb_id %><br />
    <%= f.text_field :imdb_id %>
  </div>
  <div class="field">
    <%= f.label :original_air_date %><br />
    <%= f.date_select :original_air_date %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br />
    <%= f.text_area :synopsis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Episode no</th>
    <th>Season no</th>
    <th>Series</th>
    <th>Imdb</th>
    <th>Original air date</th>
    <th>Synopsis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.name %></td>
    <td><%= episode.episode_no %></td>
    <td><%= episode.season_no %></td>
    <td><%= episode.series_id %></td>
    <td><%= episode.imdb_id %></td>
    <td><%= episode.original_air_date %></td>
    <td><%= episode.synopsis %></td>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @episode.name %>
</p>

<p>
  <b>Episode no:</b>
  <%= @episode.episode_no %>
</p>

<p>
  <b>Season no:</b>
  <%= @episode.season_no %>
</p>

<p>
  <b>Series:</b>
  <%= @episode.series_id %>
</p>

<p>
  <b>Imdb:</b>
  <%= @episode.imdb_id %>
</p>

<p>
  <b>Original air date:</b>
  <%= @episode.original_air_date %>
</p>

<p>
  <b>Synopsis:</b>
  <%= @episode.synopsis %>
</p>


<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediacore</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/series/_form.html.erb
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :imdb_id %><br />
    <%= f.text_field :imdb_id %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br />
    <%= f.text_area :synopsis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/episodes.html.erb
<%= @series.name %>
<h1>Listing episodes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Episode no</th>
    <th>Season no</th>
    <th>Series</th>
    <th>Imdb</th>
    <th>Original air date</th>
    <th>Synopsis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.name %></td>
    <td><%= episode.episode_no %></td>
    <td><%= episode.season_no %></td>
    <td><%= episode.series_id %></td>
    <td><%= episode.imdb_id %></td>
    <td><%= episode.original_air_date %></td>
    <td><%= episode.synopsis %></td>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<table>
  <tr>
    <th>Name</th>
    <th>ep count</th>
    <th>Imdb</th>
    <th>Synopsis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @series.each do |series| %>
  <tr>
    <td><%= series.name %></td>
    <td><%= series.episode_count %></td>
    <td><%= series.imdb_id %></td>
    <td><%= series.synopsis %></td>
    <td><%= link_to 'Show', series %></td>
    <td><%= link_to 'Edit', edit_series_path(series) %></td>
    <td><%= link_to 'Destroy', series, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @series.name %>
</p>

<p>
  <b>Imdb:</b>
  <%= @series.imdb_id %>
</p>

<p>
  <b>Synopsis:</b>
  <%= @series.synopsis %>
</p>


<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>